# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20160312_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
