# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='countable_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='mesurable_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_type',
            field=models.CharField(choices=[('x', 'Неделимые'), ('kg', 'Килограммы'), ('g', 'Граммы'), ('l', 'Литры'), ('ml', 'Миллилитры')], default='x', max_length=2),
        ),
    ]
